
language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"

sudo: true

before_install:
  - sudo pip install coverage --user
  - sudo pip install nosetests nose2

install:
  - sudo python setup.py install

script: nose2
  